// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2OOHmsviuYL8Uk8k4WJnHxA_C9hojBkY',
    appId: '1:627423894988:web:577ccf8771f002bedad169',
    messagingSenderId: '627423894988',
    projectId: 'expence-logger',
    authDomain: 'expence-logger.firebaseapp.com',
    databaseURL: 'https://expence-logger-default-rtdb.firebaseio.com',
    storageBucket: 'expence-logger.firebasestorage.app',
    measurementId: 'G-HVFC7V5K3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWl0FJqBQu9TqVUZp93JSz67RTiJQdfPQ',
    appId: '1:627423894988:android:9d6eebfed568781edad169',
    messagingSenderId: '627423894988',
    projectId: 'expence-logger',
    databaseURL: 'https://expence-logger-default-rtdb.firebaseio.com',
    storageBucket: 'expence-logger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGUmoy6SXVJn3vOJBLDobauXGHB7t8ZPo',
    appId: '1:627423894988:ios:8d5fe0fb94f90db5dad169',
    messagingSenderId: '627423894988',
    projectId: 'expence-logger',
    databaseURL: 'https://expence-logger-default-rtdb.firebaseio.com',
    storageBucket: 'expence-logger.firebasestorage.app',
    iosBundleId: 'com.sahid.expencelogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGUmoy6SXVJn3vOJBLDobauXGHB7t8ZPo',
    appId: '1:627423894988:ios:8d5fe0fb94f90db5dad169',
    messagingSenderId: '627423894988',
    projectId: 'expence-logger',
    databaseURL: 'https://expence-logger-default-rtdb.firebaseio.com',
    storageBucket: 'expence-logger.firebasestorage.app',
    iosBundleId: 'com.sahid.expencelogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2OOHmsviuYL8Uk8k4WJnHxA_C9hojBkY',
    appId: '1:627423894988:web:c37932359a295eaedad169',
    messagingSenderId: '627423894988',
    projectId: 'expence-logger',
    authDomain: 'expence-logger.firebaseapp.com',
    databaseURL: 'https://expence-logger-default-rtdb.firebaseio.com',
    storageBucket: 'expence-logger.firebasestorage.app',
    measurementId: 'G-3H4Z3YSV9P',
  );

}